package com.fitzone.gymbackend.enums;

public enum ActivityType {
	CUSTOMER_ARCHIVED,
	CUSTOMER_UPDATED,
	CUSTOMER_CREATED,
	MEMBERSHIP_RENEWED,
	CUSTOMER_PROFILE_UPLOADED,
	PLAN_CREATED,
	PLAN_UPDATED,
	PLAN_DEACTIVATED,
	PAYMENT_CREATED,
	PAYMENT_DELETED,
	LEAD_DELETED,
	LEAD_CREATED,
	LEAD_STATUS_UPDATED
	
}
